from typing import List, Dict, Optional

# Minimal dev split (100 items). Gold labels are "yes"/"no".
_DEV: List[Dict] = [
  {'id': 'sqa-clean-0001', 'question': 'Is Paris the capital of France?', 'answer': 'yes', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0002', 'question': 'Is the sun a planet?', 'answer': 'no', 'category': 'astronomy', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0003', 'question': 'Are whales mammals?', 'answer': 'yes', 'category': 'biology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0004', 'question': 'Do penguins live in the Sahara Desert?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0005', 'question': 'Is water composed of hydrogen and oxygen?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0006', 'question': 'Is the square root of 2 a rational number?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0007', 'question': 'Is Mount Everest part of the Himalayas?', 'answer': 'yes', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0008', 'question': 'Do cats perform photosynthesis?', 'answer': 'no', 'category': 'biology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0009', 'question': 'Is the Pacific Ocean the largest ocean on Earth?', 'answer': 'yes', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0010', 'question': 'Is paper typically made of metal?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0011', 'question': 'Is photosynthesis the process plants use to make food?', 'answer': 'yes', 'category': 'biology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0012', 'question': 'Can sound travel through a perfect vacuum?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0013', 'question': 'Is copper a metal?', 'answer': 'yes', 'category': 'chemistry', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0014', 'question': 'Is Neptune the closest planet to the sun?', 'answer': 'no', 'category': 'astronomy', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0015', 'question': 'Is zero an even number?', 'answer': 'yes', 'category': 'math', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0016', 'question': 'Is CO2 the same substance as H2O?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0017', 'question': 'Is the equator at 0 degrees latitude?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0018', 'question': 'Is a byte larger than a kilobyte?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0019', 'question': 'Is a light-year a unit of distance?', 'answer': 'yes', 'category': 'astronomy', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0020', 'question': 'Is Sydney the capital of Australia?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0021', 'question': 'Is Mercury a planet in our solar system?', 'answer': 'yes', 'category': 'astronomy', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0022', 'question': 'Is 1 a prime number?', 'answer': 'no', 'category': 'math', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0023', 'question': 'Do sharks have skeletons made of cartilage?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0024', 'question': 'Is Everest located in Africa?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0025', 'question': 'Is baking soda a base?', 'answer': 'yes', 'category': 'chemistry', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0026', 'question': 'Is helium heavier than lead?', 'answer': 'no', 'category': 'chemistry', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0027', 'question': 'Is bamboo a type of grass?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0028', 'question': 'Is the human heart located in the skull?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0029', 'question': 'Is insulin a hormone?', 'answer': 'yes', 'category': 'biology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0030', 'question': 'Is the Great Barrier Reef in the Atlantic Ocean?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0031', 'question': 'Is ice less dense than liquid water?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0032', 'question': 'Is the Amazon River in Europe?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0033', 'question': 'Is carbon central to organic chemistry?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0034', 'question': 'Is Mount Fuji in South America?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0035', 'question': 'Is HTML used to structure web pages?', 'answer': 'yes', 'category': 'technology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0036', 'question': 'Is New York City the capital of the United States?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0037', 'question': 'Is the moon smaller than Earth?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0038', 'question': 'Is Pluto larger than Jupiter?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0039', 'question': 'Is Bluetooth a wireless communication technology?', 'answer': 'yes', 'category': 'technology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0040', 'question': 'Is an octagon a seven-sided polygon?', 'answer': 'no', 'category': 'math', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0041', 'question': 'Is Jupiter larger than Earth?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0042', 'question': 'Is the equator a line of longitude?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0043', 'question': 'Is evaporation part of the water cycle?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0044', 'question': 'Is 15 an even number?', 'answer': 'no', 'category': 'math', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0045', 'question': 'Is the Nile a river?', 'answer': 'yes', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0046', 'question': 'Is glass a good breakfast?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0047', 'question': 'Is a koala a marsupial?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0048', 'question': 'Is water dry?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0049', 'question': 'Is silk produced by silkworms?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0050', 'question': 'Is the Moon made of cheese?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0051', 'question': 'Can solar panels generate electricity from sunlight?', 'answer': 'yes', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0052', 'question': 'Is 30 greater than 100?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0053', 'question': 'Is Antarctica mostly covered in ice?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0054', 'question': 'Is the capital of Spain Berlin?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0055', 'question': 'Is a decade equal to ten years?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0056', 'question': 'Is DNA an element on the periodic table?', 'answer': 'no', 'category': 'biology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0057', 'question': 'Is lava molten rock?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0058', 'question': 'Is a meter shorter than a centimeter?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0059', 'question': 'Is caffeine a stimulant?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0060', 'question': 'Is the Pacific Ocean smaller than Lake Superior?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0061', 'question': 'Is the Great Wall located in China?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0062', 'question': 'Is photosynthesis a process in animals to make meat?', 'answer': 'no', 'category': 'biology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0063', 'question': 'Is a violin a string instrument?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0064', 'question': 'Is the Eiffel Tower in Rome?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0065', 'question': 'Is the Andromeda Galaxy outside the Milky Way?', 'answer': 'yes', 'category': 'astronomy', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0066', 'question': 'Is Python exclusively a species of bird?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0067', 'question': 'Is sodium chloride common table salt?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0068', 'question': 'Is the human body composed entirely of plastic?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0069', 'question': 'Is yeast used to make bread rise?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0070', 'question': 'Is Earth the fourth planet from the sun?', 'answer': 'no', 'category': 'astronomy', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0071', 'question': 'Is a byte equal to 8 bits?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0072', 'question': 'Is a hexagon a five-sided figure?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0073', 'question': 'Is rice a cereal grain?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0074', 'question': 'Is a minute longer than an hour?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0075', 'question': 'Is Saturn known for its rings?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0076', 'question': 'Is gold magnetic under normal conditions?', 'answer': 'no', 'category': 'chemistry', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0077', 'question': 'Is granite an igneous rock?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0078', 'question': 'Is boiling water typically at 0°C at sea level?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0079', 'question': 'Is vinegar acidic?', 'answer': 'yes', 'category': 'chemistry', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0080', 'question': 'Is Mount Kilimanjaro underwater?', 'answer': 'no', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0081', 'question': 'Is a photon the quantum of light?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0082', 'question': 'Is Antarctica in the tropics?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0083', 'question': 'Is the ozone layer located in the stratosphere?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0084', 'question': 'Is silicon a liquid at room temperature?', 'answer': 'no', 'category': 'chemistry', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0085', 'question': 'Is chlorophyll green?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0086', 'question': 'Is Everest shorter than a common house?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0087', 'question': 'Is a keyboard an input device?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0088', 'question': 'Is a circle composed of straight line segments?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0089', 'question': 'Is Mars nicknamed the Red Planet?', 'answer': 'yes', 'category': 'astronomy', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0090', 'question': 'Is a compass used to eat soup?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0091', 'question': 'Is JSON a data interchange format?', 'answer': 'yes', 'category': 'technology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0092', 'question': 'Is the Taj Mahal located in Brazil?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0093', 'question': 'Is Pakistan in South Asia?', 'answer': 'yes', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0094', 'question': 'Is the Sahara in Greenland?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0095', 'question': 'Is the Suez Canal in Egypt?', 'answer': 'yes', 'category': 'geography', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0096', 'question': 'Is oxygen unnecessary for human life?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0097', 'question': 'Is TypeScript a superset of JavaScript?', 'answer': 'yes', 'category': 'technology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0098', 'question': 'Is photosynthesis driven by moonlight rather than sunlight?', 'answer': 'no', 'category': 'biology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0099', 'question': 'Is a resistor used to limit electric current?', 'answer': 'yes', 'category': 'technology', 'temporal_scope': 'timeless'},
  {'id': 'sqa-clean-0100', 'question': 'Is water’s chemical formula H3O under normal naming?', 'answer': 'no', 'category': 'general', 'temporal_scope': 'timeless'},
]

def load(split: str = "dev", limit: Optional[int] = None) -> List[Dict]:
    if split != "dev":
        raise NotImplementedError("StrategyQA full split will be plugged later.")
    data = _DEV if limit is None else _DEV[:limit]
    # Standardized fields expected by the harness
    return [{"id": ex["id"], "question": ex["question"], "answer": ex["answer"], "meta": {"dataset": "strategyqa"}} for ex in data]
